defaults:
  - environment: lunalab
  - rendering: ray_tracing
  - mode: ROS2
  - physics: default_physics
  - optional robot: null
  - optional controller: null
  
hydra:
  output_subdir: null
  run:
    dir: .
