[workspace]
authors = ["Shamistan Karimov <ahresgg@gmail.com>"]
channels = ["conda-forge"]
name = "OmniLRS"
platforms = ["linux-64"]
version = "0.1.0"
description = "Pixi environments for OmniLRS with Isaac Sim 5 and manager-specific features"

[system-requirements]
libc = { family = "glibc", version = "2.35" }

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy = "unsafe-best-match"

# common deps, tasks, env variables in feature "core"
[feature.core.dependencies]
python = "3.11.*"
gdal = "*"
libgdal = "*"

[feature.core.pypi-dependencies]
opencv-python = "*"
omegaconf = "*"
hydra-core = "*"
skyfield = "*"
zfpy = "*"
numba = "*"
gdown = "*"
em = "*"
lark = "*"
pandas = "*"
OmniLRS = { path = ".", editable = true }

[feature.core.activation.env]
OMNILRS_ROOT = "${PIXI_PROJECT_ROOT}"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

# isaacsim-specific deps, tasks, env variables in feature "isaac"
[feature.isaac.dependencies]
packaging = "==23.0"
numpy = "==1.26.0"

[feature.isaac.pypi-dependencies]
isaacsim = { version = "==5.0.0", extras = ["all", "extscache"] }

[feature.isaac.activation.env]
OMNI_KIT_ACCEPT_EULA = "YES"

[feature.isaac.tasks]
isaacsim = "isaacsim"

# ros2-specific tasks, env variables in feature "ros2"
[feature.ros2.activation]
scripts = ["scripts/activate_isaac_ros.sh"]

[feature.ros2.activation.env]
ROS_DISTRO = "humble"
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"

[feature.ros2.tasks]
ros2 = "python run.py mode=ROS2"

# yamcs-specific deps, tasks in feature "yamcs"
[feature.yamcs.pypi-dependencies]
yamcs-client = "*"

[feature.yamcs.tasks]
yamcs = "python run.py mode=Yamcs environment=lunaryard_40m_workshop"

# zenoh-specific deps, tasks in feature "zenoh"
[feature.zenoh.pypi-dependencies]
eclipse-zenoh = "*"
asyncio_for_robotics = "*"
msgspec = "*"

[feature.zenoh.tasks]
zenoh = "python run.py mode=Zenoh environment=lunalab_zenoh"

[environments]
default = { features = ["core", "isaac"] }
yamcs = { features = ["core", "isaac", "yamcs"] }
zenoh = { features = ["core", "isaac", "zenoh"] }
ros2 = { features = ["core", "isaac", "ros2"] }
