from __future__ import annotations
from typing import Any, Dict, Protocol


class Transport(Protocol):
    def start(self) -> None: ...
    def publish(self, frame: Dict[str, Any]) -> None: ...
    def close(self) -> None: ...
